LUI-UI/lui-vue

.eslintrc.cjs, package.json, src/App.vue, src/components/Badge/LuiBadge.stories.js, src/components/Badge/LuiBadge.vue, src/components/Button/LuiButton.vue, src/components/Button/__tests__/LuiButton.spec.ts, src/components/Checkbox/composables/index.ts, src/components/Icon/LuiIcon.vue, src/components/Input/composables/index.ts, src/composables/index.ts, src/global-interfaces.ts, src/global-types.ts, src/stories/Header.stories.js, src/stories/Header.vue, src/stories/Page.stories.js, src/stories/Page.vue, vite.config.ts, yarn.lock
Clear Lint error, clear package.json, clear unused variables, clear console, LuiBadge created
=> LuiBadge  & Fix Lint Errors

.github/workflows/pr_check.yaml, CHANGELOG.md, package.json
Feature
Checks overall
Creates a pull request check
No
=> 36 we need create a action which works before every pull requestnew action

src/components/Select/LuiOption.vue
=> fix(option): add cursor-pointer to option

src/components/Select/LuiOption.vue
=> fix(option): remove unnecesary lines

src/components/Select/LuiOption.vue
=> fix(option): remove unnecesary line

.storybook/global-story-argtypes.ts, src/components/Badge/LuiBadge.stories.ts, src/components/Button/LuiButton.stories.ts, src/components/Checkbox/LuiCheckbox.stories.ts, src/components/Input/LuiInput.stories.ts, src/components/Menu/LuiMenu.stories.ts, src/components/Radio/LuiRadio.stories.ts, src/components/Select/LuiSelect.stories.ts, src/components/Switch/LuiSwitch.stories.ts, src/components/Tabs/LuiTab.stories.ts, src/components/Textarea/LuiTextarea.stories.ts
=> fix(stroybook): remove storybook deprecated argtypes

src/components/Menu/LuiMenuDropdown.vue
=> 50 focus issue on dropdown with custom trigger

src/components/Checkbox/LuiCheckbox.vue, src/components/Checkbox/composables/index.ts
=> fix(luicheckbox): checkbox check icon dark mode color fix

src/components/Modal/LuiModal.vue
=> 74 modal component does not toggle body overflow

src/components/Input/LuiInput.vue, src/components/Input/composables/index.ts, src/components/Input/input-types.ts, src/components/Select/LuiOption.vue, src/components/Select/LuiSelect.stories.ts, src/components/Select/LuiSelect.vue, src/components/Select/select-types.ts, src/utils/hasSlotContent.ts
=> 66 we need make searchable to lui selectselect

src/components/Modal/LuiModal.vue
=> fix(modal): fix modal aria-labelledby issue

src/components/Select/LuiSelect.vue
=> 89 select unnecessary data field

src/components/Input/LuiInput.vue, src/components/Input/composables/index.ts, src/components/Select/LuiSelect.vue, src/utils/hasSlotContent.ts
Change the utils to check properly the content of slot
#92
=> fix(utils): change hasSlotContent utils

src/components/Menu/LuiMenu.stories.ts, src/components/Menu/LuiMenuDropdown.vue
Add main container to w-full class if block prop is true
#97
=> fix(menudropdown): fix menudropdown block prop issue

src/components/Modal/LuiModal.vue
=> feat(modal): add padding prop to make padding removeable

src/components/Modal/LuiModal.vue
=> feat(modal): add a prop to make removeable border-radius

src/components/Modal/LuiModal.vue, src/components/Select/LuiSelect.stories.ts
=> feat(modal): add fullScreen prop

src/components/Modal/LuiModal.vue
=> feat(modal): change lui-modal size

src/components/Select/LuiSelect.vue
There was a bug with the template, fix the bug by adding extra wrapper and v-if
#115
=> fix(select): fix nothing found text always shown issue

src/components/Menu/LuiMenuDropdown.vue
=> fix(menudropdown): fix prepend, append slots

src/components/Select/LuiSelect.vue
=> fix(select): add prepend slot and make prepend slot closable

src/components/Modal/LuiModal.vue
add relative class to dialog be able to position custom close buttons with absolute positining
#112
=> fix(modal): made available to add custom close button

src/components/Select/LuiSelect.vue
=> fix(select): fix change event initial trigger issue

src/components/Select/LuiSelect.vue
=> fix(select): fix state-icon bug

src/components/Overlay/LuiOverlay.stories.ts, src/components/Overlay/LuiOverlay.vue, src/plugin/lui-ui.js
=> 122 we need overlay componentnew component

src/components/Checkbox/LuiCheckbox.stories.ts, src/components/Checkbox/LuiCheckbox.vue, src/components/Overlay/LuiOverlay.vue
=> 81 luicheckbox value props type error

src/components/Overlay/LuiOverlay.stories.ts, src/components/Overlay/LuiOverlay.vue
=> fix(overlay): change overlay component to compatible modals

package.json
=> fix(storybook): change storybook deploy script in package.json

package.json
=> fix(storybook): change build storuybook script

src/components/Button/LuiButton.stories.ts, src/components/Button/LuiButton.vue, src/components/Button/button-types.ts
=> fix(button): add a and span in button tag types

src/components/Button/LuiButton.vue, src/components/Button/button-types.ts, src/components/Button/composables/index.ts
=> fix(luibutton): fix LuiButton Tag types

src/components/MenuDropdown/LuiMenuDropdown.stories.ts, src/components/MenuDropdown/LuiMenuDropdown.vue, src/components/MenuItem/LuiMenuItem.vue
=> fix(dropdown): fix lint

src/components/Radio/LuiRadio.vue
=> fix(radio): fix radio initial selection bug

src/components/Avatar/LuiAvatar.stories.ts, src/components/Avatar/LuiAvatar.vue, src/components/Popover/LuiPopover.stories.ts
=> fix(avatar): change avatar sizes

src/components/Tabs/LuiTab.stories.ts, src/components/Tabs/LuiTabButton.vue, src/components/Tabs/LuiTabButtons.vue, src/components/Tabs/LuiTabGroup.vue
=> feat(tab): make tab-buttons and tab-button customizable

src/components/Popover/LuiPopover.stories.ts, src/components/Popover/LuiPopover.vue
=> fix(popover): add block prop

src/components/Popover/LuiPopover.vue, src/composables/useElementSize.ts, src/composables/useProperPosition.ts
=> fix(popover): fix popover focus-trap bug

src/composables/useProperPosition.ts
=> fix(useproperposition): fix proper position bug

src/components/Popover/LuiPopover.vue
=> fix(popover): fix popover z-index issue

src/components/Select/LuiSelect.vue
=> fix(type): fix type error

src/components/Popover/LuiPopover.stories.ts, src/components/Popover/LuiPopover.vue
=> fix(popover): fix popover component block prop

src/components/MultiSelect/LuiMultiSelect.vue, src/components/Tag/LuiTag.vue
=> fix(multiselet): fix searchable prop when using placeholder

src/components/MenuItem/LuiMenuItem.stories.ts, src/components/MenuItem/menu-item-types.ts
=> fix(menuitem): add new options for menuitem tag prop

src/components/Popover/LuiPopover.vue
=> fix(popover): add on-trigger event to popover component

src/components/MultiSelect/LuiMultiSelect.vue, src/components/Option/LuiOption.vue
=> fix(multi-select): fix model-value changes bug

.github/workflows/release.yaml
=> fix(release.yaml): fix release yaml

src/components/MultiSelect/LuiMultiSelect.stories.ts, src/components/MultiSelect/LuiMultiSelect.vue, src/components/Option/LuiOption.vue, src/components/Select/LuiSelect.stories.ts, src/components/Select/LuiSelect.vue, src/components/Select/select-types.ts
=> fix(select,multi-select): handle usage of different text and value

src/components/Popover/LuiPopover.stories.ts, src/composables/useElementPosition.ts, src/composables/useMenuPositionStyles.ts
=> fix(menustyle): fix menu style resize bug

src/components/Modal/LuiModal.vue
=> fix(modal): add be able to close with esc and outside click

src/components/MenuDropdown/LuiMenuDropdown.stories.ts, src/components/MenuDropdown/LuiMenuDropdown.vue, src/components/MultiSelect/LuiMultiSelect.stories.ts, src/components/MultiSelect/LuiMultiSelect.vue, src/components/Popover/LuiPopover.stories.ts, src/components/Popover/LuiPopover.vue, src/components/Select/LuiSelect.stories.ts, src/components/Select/LuiSelect.vue
=> fix(menu-components): control open state on menu components

package.json, pnpm-lock.yaml, src/components/Checkbox/LuiCheckbox.vue, src/components/Checkbox/composables/index.ts, src/components/Radio/LuiRadio.vue, src/components/Radio/composables/index.ts, src/components/Switch/composables/index.ts, src/plugin/lui-ui.js
=> fix(checkbox,radio): fix disabled issue

src/components/Avatar/LuiAvatar.vue, src/components/Input/LuiInput.vue, src/components/MenuDropdown/LuiMenuDropdown.vue, src/components/Sidebar/LuiSidebar.vue, tsconfig.json
=> 247 missing teleport prop on sidebar

packages/vue/src/components/MenuDropdown/LuiMenuDropdown.vue, packages/vue/src/components/MultiSelect/LuiMultiSelect.vue, packages/vue/src/components/Popover/LuiPopover.vue, packages/vue/src/components/Select/LuiSelect.vue
=> fix(vue): fix menu animations

packages/vue/src/components/Popover/LuiPopover.vue
=> fix(vue): fix popover componetent teleport issue

packages/vue/src/components/Select/LuiSelect.stories.ts, packages/vue/src/components/Select/LuiSelect.vue
=> fix(vue): add clearable prop to select

packages/vue/src/components/Sidebar/LuiSidebar.vue
=> fix(vue): remove sidebar outside padding

packages/vue/src/components/Radio/LuiRadio.vue, packages/vue/src/components/Select/LuiSelect.vue
=> fix(vue): fix select search input selection style, fix radio vmodel type

packages/vue/src/components/MenuDropdown/LuiMenuDropdown.vue, packages/vue/src/components/MultiSelect/LuiMultiSelect.vue, packages/vue/src/components/Popover/LuiPopover.vue, packages/vue/src/components/Select/LuiSelect.vue
=> fix: fix all menu component dissepear issue

packages/vue/src/components/MultiSelect/LuiMultiSelect.vue
=> fix: clear function on tag

packages/vue/src/components/Tabs/LuiTabGroup.vue
=> feat: scroll active tab on mobile

packages/vue/src/components/Input/LuiInput.vue, packages/vue/src/components/Modal/LuiModal.vue, packages/vue/src/components/Sidebar/LuiSidebar.vue
=> feat: add aria label for icon buttons

packages/vue/src/components/MultiSelect/LuiMultiSelect.vue, packages/vue/src/components/Select/LuiSelect.stories.ts, packages/vue/src/components/Select/LuiSelect.vue
=> fix: prevent modelValue update on initial render

packages/vue/src/components/MenuItem/LuiMenuItem.vue, packages/vue/src/components/Tabs/LuiTabButton.vue
=> fix: fix template for manage aria-attributes correctly

packages/vue/src/components/Tabs/LuiTab.stories.ts, packages/vue/src/components/Tabs/LuiTabButtons.vue, packages/vue/src/components/Tabs/LuiTabGroup.vue, packages/vue/src/components/Tabs/symbols.ts, packages/vue/src/components/Tabs/types.ts
=> fix: prevent initial page scroll
